add_subdirectory(dot-product)
add_subdirectory(test)
add_subdirectory(AlexNet-ImageNet)
add_subdirectory(boolean-and-batch-test)
add_subdirectory(andk-test)
add_subdirectory(PrefixAND-test)
add_subdirectory(PrefixOR-test)
add_subdirectory(LTBits-test)
add_subdirectory(FpShare)
add_subdirectory(FpCircuit-test)
add_subdirectory(LTBitsFp-test)
add_subdirectory(GtzGate-test)
add_subdirectory(LTBitsFp-exp)